/* Generated By:JavaCC: Do not edit this line. Edb_Query_ParserTreeConstants.java Version 5.0 */
package cyclients.edb.ParseExprTree.ASTree;

public interface Edb_Query_ParserTreeConstants
{
  public int JJTDBQUERY = 0;
  public int JJTDBSFWSTATEMENT = 1;
  public int JJTDBSELECTCLAUSE = 2;
  public int JJTVOID = 3;
  public int JJTDBATTR = 4;
  public int JJTDBRELVAR = 5;
  public int JJTDBRELNAME = 6;
  public int JJTDBATTRNAME = 7;
  public int JJTDBRELALIASNAME = 8;
  public int JJTDBFROMCLAUSE = 9;
  public int JJTDBWHERECLAUSE = 10;
  public int JJTBOOLEANFACTOR = 11;
  public int JJTNOT = 12;
  public int JJTAND = 13;
  public int JJTOR = 14;
  public int JJTCOMPARISONOP = 15;
  public int JJTDBCONSTVALUE = 16;
  public int JJTINTEGERLITERAL = 17;
  public int JJTFLOATLITERAL = 18;
  public int JJTSTRINGLITERAL = 19;


  public String[] jjtNodeName = {
    "dbQuery",
    "dbSFWStatement",
    "dbSelectClause",
    "void",
    "dbAttr",
    "dbRelVar",
    "dbRelName",
    "dbAttrName",
    "dbRelAliasName",
    "dbFromClause",
    "dbWhereClause",
    "BooleanFactor",
    "NOT",
    "AND",
    "OR",
    "comparisonOp",
    "dbConstValue",
    "INTEGERLITERAL",
    "FLOATLITERAL",
    "STRINGLITERAL",
  };
}
/* JavaCC - OriginalChecksum=d6e2ac51f42f1c2d38e4a3f522e894c2 (do not edit this line) */
